trigger:
- feature/azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  - dotvvm.root: ${{ Pipeline.Workspace }}
  - build.configuration: Release

container:
  image: registry.gitlab.com/cafstep/dotvvm-test/dotvvm

jobs:
  - job: build-crossplatform
    steps:
      - script: npm ci --cache $(dotvvm.root)/.npm --prefer-offline
        workingDirectory: src/DotVVM.Framework
      - script: npm run build
        workingDirectory: src/DotVVM.Framework
      - script: dotnet restore --packages $(dotvvm.root)/.nuget src/Crossplatform.sln
      - script: dotnet build --no-restore --configuration $(build.configuration) src/Crossplatform.sln

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
