trigger:
- feature/azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  DOTVVM_ROOT: ${{ Pipeline.Workspace }}
  BUILD_CONFIGURATION: Release

container:
  image: registry.gitlab.com/cafstep/dotvvm-test/dotvvm

jobs:
  - job: build-crossplatform
    steps:
      - script: npm ci --cache $(DOTVVM_ROOT)/.npm --prefer-offline
        workingDirectory: src/DotVVM.Framework
      - script: npm run build
        workingDirectory: src/DotVVM.Framework
      - script: dotnet restore --packages $(DOTVVM_ROOT)/.nuget src/Crossplatform.sln
      - script: dotnet build --no-restore --configuration $(BUILD_CONFIGURATION) src/Crossplatform.sln
