apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotvvm-ci-api
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: dotvvm-ci-api
    spec:
      containers:
      - name: dotvvm-ci-api
        image: dotvvmci.azurecr.io/dotvvm.samples.basicsamples.api.aspnetcore:latest
        imagePullPolicy: Always        
        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: azurecontainerreg